In [1]:
import torch


In [3]:

a = torch.randint(1,10, size=(3,4,5))


In [5]:
masks_a = (a % 2 == 0)

In [6]:
masks_a

tensor([[[False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False,  True, False, False, False],
         [False, False, False,  True, False]],

        [[ True,  True, False,  True,  True],
         [False,  True,  True, False,  True],
         [False, False, False,  True, False],
         [False,  True, False, False, False]],

        [[ True, False,  True, False,  True],
         [False, False, False, False,  True],
         [ True,  True, False, False, False],
         [ True, False, False, False, False]]])

In [7]:
b = a.clone().detach()


In [9]:
b.masked_fill(masks_a == 0, -1e9)


tensor([[[-1000000000, -1000000000, -1000000000,           2,           8],
         [-1000000000, -1000000000, -1000000000, -1000000000,           2],
         [-1000000000,           8, -1000000000, -1000000000, -1000000000],
         [-1000000000, -1000000000, -1000000000,           4, -1000000000]],

        [[          4,           2, -1000000000,           8,           2],
         [-1000000000,           2,           2, -1000000000,           2],
         [-1000000000, -1000000000, -1000000000,           2, -1000000000],
         [-1000000000,           8, -1000000000, -1000000000, -1000000000]],

        [[          4, -1000000000,           8, -1000000000,           6],
         [-1000000000, -1000000000, -1000000000, -1000000000,           4],
         [          8,           4, -1000000000, -1000000000, -1000000000],
         [          6, -1000000000, -1000000000, -1000000000, -1000000000]]])

In [13]:
masks_b = masks_a[:,0,:]

In [18]:
masks_b1 = masks_b.unsqueeze(-2)


In [21]:
masks_b1

tensor([[[False, False, False,  True,  True]],

        [[ True,  True, False,  True,  True]],

        [[ True, False,  True, False,  True]]])

In [20]:
b.masked_fill(masks_b1, -1e9)

tensor([[[          9,           3,           9, -1000000000, -1000000000],
         [          3,           3,           3, -1000000000, -1000000000],
         [          9,           8,           5, -1000000000, -1000000000],
         [          1,           9,           1, -1000000000, -1000000000]],

        [[-1000000000, -1000000000,           5, -1000000000, -1000000000],
         [-1000000000, -1000000000,           2, -1000000000, -1000000000],
         [-1000000000, -1000000000,           9, -1000000000, -1000000000],
         [-1000000000, -1000000000,           9, -1000000000, -1000000000]],

        [[-1000000000,           3, -1000000000,           5, -1000000000],
         [-1000000000,           1, -1000000000,           9, -1000000000],
         [-1000000000,           4, -1000000000,           7, -1000000000],
         [-1000000000,           5, -1000000000,           7, -1000000000]]])